image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "urbanlife"
  CONTAINER_NAME: "urbanlife"
  CONTAINER_PORT: "8888"

build:
  stage: build
  before_script:
    - if lsof -i :8888 | grep -q 'LISTEN'; then sudo pkill -f "LISTEN"; fi
    - docker stop urbanlife
    - docker rm -f urbanlife
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  script:
    - docker run -d -p $CONTAINER_PORT:5040 --name $CONTAINER_NAME $DOCKER_IMAGE_NAME