image: docker:stable

stages:
  - build
  - deploy
  - test

variables:
  DOCKER_IMAGE_NAME: "urbanlife:latest"
  CONTAINER_NAME: "urbanlife"
  CONTAINER_PORT: "80"

build:
  stage: build
  tags:
    - equipo5
  only:
    - front
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - docker stop $CONTAINER_NAME || true
    - docker rm -f $CONTAINER_NAME || true
    - docker rmi $DOCKER_IMAGE_NAME || true
    - docker rmi $(docker images -f "dangling=true" -q) || true
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  tags:
    - equipo5
  only:
    - front
  services:
    - name: docker:dind
      alias: docker
  script:
    - docker run -d -p $CONTAINER_PORT:5040 --name $CONTAINER_NAME $DOCKER_IMAGE_NAME

test:
  stage: test
  tags:
    - equipo5
  services:
    - name: docker:dind
      alias: docker
  only:
    - front
  script:
    - docker images | grep $DOCKER_IMAGE_NAME
    - docker ps -a | grep $CONTAINER_NAME
