image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "urbanlife:latest"

before_script:
  - CONTAINER_ID=$(docker ps -q -f "publish=443")
  - if [ -n "$CONTAINER_ID" ]; then docker stop $CONTAINER_ID && docker rm $CONTAINER_ID; fi

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  script:
    - docker run -d -p 443:5040 $DOCKER_IMAGE_NAME
