image: docker:stable

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "urbanlife:latest"
  CONTAINER_NAME: "urbanlife"
  CONTAINER_PORT: "80"

build:
  stage: build
  tags:
    - equipo5
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - 'if [[ "$(docker ps -q -f "publish=$CONTAINER_PORT")" ]]; then docker stop $(docker ps -q -f "publish=$CONTAINER_PORT"); fi'
    - 'if [[ "$(docker ps -aq -f "publish=$CONTAINER_PORT" -f status=exited)" ]]; then docker rm $(docker ps -aq -f "publish=$CONTAINER_PORT" -f status=exited); fi'
    - docker stop $CONTAINER_NAME || true
    - docker rm -f $CONTAINER_NAME || true
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  tags:
    - equipo5
  services:
    - name: docker:dind
      alias: docker
  script:
    - docker run -d -p $CONTAINER_PORT:5040 --name $CONTAINER_NAME $DOCKER_IMAGE_NAME