image: docker:stable

variables:
  DOCKER_NAME: "equipo-05_urbanlife"

stages:
  - build

build:
  stage: build
  tags:
    - equipo5back
  only:
    - back
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - docker rmi -f equipo-05-urbanlife || true
    - docker stop  equipo-05-urbanlife-1 || true
    - docker stop  equipo-05-db-1 || true
    - docker rm -f equipo-05-urbanlife-1 equipo-05-db-1 || true
    - docker ps -a -q -f status=exited | xargs docker rm
    - apk add --no-cache curl
    - dangling_images=$(docker images -f "dangling=true" -q)
    - if [ -n "$dangling_images" ]; then docker rmi $dangling_images || true; fi
    - |
      curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
  script:
    - docker-compose up --build -d
    - docker start equipo-05-urbanlife-1
