images: docker:latest

stages:
  - stop_container
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "urbanlife:latest"
  CONTAINER_PORT: "8080"

stop_container:
  stage: stop_container
  script:
    - CONTAINER_ID=$(docker ps -q -f "expose=$CONTAINER_PORT")
    - if [ -n "$CONTAINER_ID" ]; then docker stop $CONTAINER_ID; fi
    - if [ -n "$CONTAINER_ID" ]; then docker rm $CONTAINER_ID; fi

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  script:
    - docker run -d -p $CONTAINER_PORT:5040 $DOCKER_IMAGE_NAME
