image: docker:stable

variables:
  DOCKER_NAME: "equipo-05_urbanlife"

stages:
  - build

build:
  stage: build
  tags:
    - equipo5back
  only:
    - back
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - docker --version
    - apt install docker-compose
  script:
    - docker-compose up -d --build
