image: docker:latest

stages:
  - stop_container
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "urbanlife:latest"
  CONTAINER_PORT: "8080"

stop_container:
  stage: stop_container
  script:
    - if lsof -i :$CONTAINER_PORT | grep -q 'docker-pr'; then sudo pkill -f "docker-pr"; fi
    - CONTAINER_ID=$(docker ps -q --filter "expose=$CONTAINER_PORT")
    - for CONTAINER_ID in $CONTAINER_IDS; do
        docker stop $CONTAINER_ID || true
        docker rm -f $CONTAINER_ID || true
    - done

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  script:
    - docker run -d -p $CONTAINER_PORT:5040 $DOCKER_IMAGE_NAME
