image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t urbanlife .
    - docker tag urbanlife registry.gitlab.com/urbanlife/urbanlife:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker push registry.gitlab.com/urbanlife/urbanlife:latest

test:
  stage: test
  script:
    - docker run --rm urbanlife pytest
  only:
    - front

deploy:
  stage: deploy
  script:
    - docker run --rm urbanlife deploy.sh
  only:
    - front