image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "urbanlife"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  script:
    - docker run -d -p 80:5040 $DOCKER_IMAGE_NAME