image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "urbanlife"
  CONTAINER_NAME: "urbanlife"
  CONTAINER_PORT: "8888"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  script:
    - docker stop urbanlife
    - docker rm -f urbanlife
    - systemctl restart docker
    - docker run -d -p $CONTAINER_PORT:5040 --name $CONTAINER_NAME $DOCKER_IMAGE_NAME