image: docker:stable

variables:
  DOCKER_NAME: "equipo-05_urbanlife"

stages:
  - build

build:
  stage: build
  tags:
    - equipo5back
  only:
    - back
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - docker --version
    - docker rmi -f equipo-05-urbanlife:latest
    - apk add --no-cache curl
    - |
      # Install Docker Compose
      curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
      docker-compose --version
  script:
    - docker-compose up -d --build