image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: urbanlife
  SSH_KEY_PATH: /home/ubuntu/e5-clave.pem
  REMOTE_SERVER_IP: 35.173.196.9

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
  only:
    - front

deploy:
  stage: deploy
  script:
   - docker save $DOCKER_IMAGE_NAME | gzip -c > $DOCKER_IMAGE_NAME.tar.gz
    - scp -i $SSH_KEY_PATH $DOCKER_IMAGE_NAME.tar.gz ubuntu@$REMOTE_SERVER_IP:~/
    - ssh -i $SSH_KEY_PATH ubuntu@$REMOTE_SERVER_IP 'docker load -i ~/$DOCKER_IMAGE_NAME.tar.gz'
    - ssh -i $SSH_KEY_PATH ubuntu@$REMOTE_SERVER_IP "docker run -d -p 443:5040 --name $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME"
  only:
    - front





