image: docker:latest

stages:
  - build
  - stop_runner
  - deploy

variables:
  DOCKER_IMAGE_NAME: "urbanlife:latest"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

stop_runner:
  stage: stop_runner
  script:
    - |
      PID_TO_KILL=$(ps aux | grep '[g]itlab-runner' | awk '{print $2}')
      if [ -n "$PID_TO_KILL" ]; then
        echo "Deteniendo gitlab-runner con PID $PID_TO_KILL"
        sudo kill -9 $PID_TO_KILL
      else
        echo "No se encontró el proceso gitlab-runner"
      fi

deploy:
  stage: deploy
  script:
    - docker run -d -p 443:5040 $DOCKER_IMAGE_NAME
