image: docker:latest

stages:
  - stop_runner
  - build
  - stop_container
  - deploy

variables:
  DOCKER_IMAGE_NAME: "urbanlife:latest"

stop_runner:
  stage: stop_runner
  script:
    - killall -9 gitlab-ru

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

stop_container:
  stage: stop_container
  script:
    - CONTAINER_ID=$(docker ps -q -f "expose=443")
    - if [ -n "$CONTAINER_ID" ]; then docker stop $CONTAINER_ID; fi
    - if [ -n "$CONTAINER_ID" ]; then docker rm $CONTAINER_ID; fi

deploy:
  stage: deploy
  script:
    - docker run -d -p 443:5040 $DOCKER_IMAGE_NAME
