image: docker:stable

variables:
  DOCKER_NAME: "equipo-05_urbanlife"

stages:
  - build

build:
  stage: build
  tags:
    - equipo5back
  only:
    - back
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - snap install docker
    - apt install docker-compose
    - docker stop $DOCKER_NAME || true
    - docker rm -f $DOCKER_NAME || true
    - docker rmi $DOCKER_NAME || true
    - dangling_images=$(docker images -f "dangling=true" -q)
    - if [ -n "$dangling_images" ]; then docker rmi $dangling_images || true; fi
  script:
    - docker-compose up -d --build
