image: docker:stable

stages:
  - build
  - test

build:
  stage: build
  tags:
    - equipo5back
  only:
    - back
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - docker rm -f $(docker ps -aq) || true
    - docker rmi -f $(docker images -q) || true
  script:
    - docker-compose up -d --build
