stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t urbanlife .

deploy:
  stage: deploy
  script:
    - docker save urbanlife | gzip -c > urbanlife.tar.gz
    - scp -i /home/ubuntu/e5-clave.pem urbanlife.tar.gz ubuntu@18.232.157.54:~/urbanlife.tar.gz
    - ssh -i /home/ubuntu/e5-clave.pem ubuntu@18.232.157.54 'docker load -i /home/ubuntu/urbanlife.tar.gz'
    - ssh -i /home/ubuntu/e5-clave.pem ubuntu@18.232.157.54 'docker run -d -p 80:80 urbanlife'
