export const routes = {
  home: "/",
  detail: "product/:id",
  categoria: "categoria/:id",
  notFound: "*",
  admin: "admin",
  listaProductos: "listaproductos",
  añadirProducto: "añadirproducto",
  categorias: "categorias",
  añadirCategorias: "añadircategorias",
  imgCategoria: "imgcategoria",
  listarCategorias: "listarcategorias",
  añadirTalles: "añadirtalles",
  editarProducto: "editarproducto/:idProducto",
  login: "login",
  registro: "registro",
};
